### ISSUE TITLE
Unable to reproduce preprocessing for Table 1 data statistics

### ISSUE THREAD

**Issue by ktxlh** [amzn/faithful-data2text-cycle-training#2]
I use the DART data from HuggingFace (https://huggingface.co/datasets/dart). Following your description for data preprocessing, I am able to get the right statistics for WebNLG, right number of train and val instances for E2E, but not the other numbers in Table 1 (e.g. number of instances for all DART/Wiki* datasets, number of unique predicates, etc. -- which is as low as just 7 for e2e!)

In Section 4.1 of your paper, you mention that you "drop some WSQL and WTQ samples that contain non-conventional structural tags." Can you define "non-conventional" please? The term "conventional" is vague and undefined.

**Comment by Edillower** [comment]
Howdy!
Sorry for the confusion. For WSQL and WTQ, we dropped samples containing tags like [TABLECONTEXT], [TITLE], etc. (those wrapped by square brackets) to ensure that we have samples with proper subject-predicate-object triplets as we have for WebNLG and E2E. 

Thanks,
Zhuoer Wang

**Comment by ktxlh** [comment]
What is the exact data format fed into cycle training? For example, if there are multiple triplets for a text, do you concatnate them with 1. 2., ... and \n like what you show in Table 6?

**Comment by Edillower** [comment]
Yes, we just concat the linearized triplets of a sample. It was concatenated with space instead of \n for easier processing of the input files. However, using \n is also fine, and I think it would make little difference to the final results.

**Comment by ktxlh** [comment]
So for yes, you mean you do have "1. 2., ..." etc in front of each triplet?

**Comment by ktxlh** [comment]
I see. Thanks. Can you provide a small sample of preprocessed data (e.g. few rows) please?

**Comment by Edillower** [comment]
See: https://github.com/Edillower/CycleNLG/issues/1#issuecomment-1828870476

**Comment by ktxlh** [comment]
Got it. Thanks a lot!!
